name: Deploy Project
on:
  push:
    branches: [main]
    tags: ['v*.*.*'] # Trigger on version tags too!

jobs:
  call-docker-build:
    uses: YanyanLiuBio/actions-library/.github/workflows/docker-reusable.yml@main
    with:
      image_name: "test-py"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}